// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"example.com/local/Go2part/internal/legalentities"
	"example.com/local/Go2part/internal/web/olegalentity"
	"github.com/google/wire"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	db, err := NewDB()
	if err != nil {
		return nil, err
	}
	repository := legalentities.NewRepository(db)
	service := legalentities.NewService(repository)
	legalEntityHandler := olegalentity.NewLegalEntityHandler(service)
	engine := NewRouter(legalEntityHandler)
	app := NewApp(engine)
	return app, nil
}

// wire.go:

var appSet = wire.NewSet(
	NewApp,
	NewRouter,
	NewDB, legalentities.NewRepository, legalentities.NewService, wire.Bind(new(legalentities.ServiceInterface), new(*legalentities.Service)), olegalentity.NewLegalEntityHandler, wire.Bind(new(olegalentity.ServerInterface), new(*olegalentity.LegalEntityHandler)),
)
