// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"example.com/local/Go2part/internal/legalentities"
	"example.com/local/Go2part/internal/web"
	"example.com/local/Go2part/pkg/postgres"
)

// Injectors from wire.go:

func InitLegalEntityHandler(dsn string) *web.LegalEntityHandler {
	db := postgres.NewSQLiteConnection(dsn)
	gormRepository := legalentities.NewGormRepository(db)
	service := legalentities.NewService(gormRepository)
	legalEntityHandler := web.NewLegalEntityHandler(service)
	return legalEntityHandler
}
