// Package olegalentity provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package olegalentity

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateLegalEntity defines model for CreateLegalEntity.
type CreateLegalEntity struct {
	Name string `json:"name"`
}

// LegalEntity defines model for LegalEntity.
type LegalEntity struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Name      *string    `json:"name,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Uuid      *UUID      `json:"uuid,omitempty"`
}

// UUID defines model for UUID.
type UUID = openapi_types.UUID

// UpdateLegalEntity defines model for UpdateLegalEntity.
type UpdateLegalEntity struct {
	Name string `json:"name"`
}

// Limit defines model for limit.
type Limit = int

// Offset defines model for offset.
type Offset = int

// GetLegalEntitiesParams defines parameters for GetLegalEntities.
type GetLegalEntitiesParams struct {
	// Limit Max items to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset from start
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostLegalEntitiesJSONRequestBody defines body for PostLegalEntities for application/json ContentType.
type PostLegalEntitiesJSONRequestBody = CreateLegalEntity

// PutLegalEntitiesUuidJSONRequestBody defines body for PutLegalEntitiesUuid for application/json ContentType.
type PutLegalEntitiesUuidJSONRequestBody = UpdateLegalEntity

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all legal entities
	// (GET /legal-entities)
	GetLegalEntities(c *gin.Context, params GetLegalEntitiesParams)
	// Create legal entity
	// (POST /legal-entities)
	PostLegalEntities(c *gin.Context)
	// Delete legal entity by UUID
	// (DELETE /legal-entities/{uuid})
	DeleteLegalEntitiesUuid(c *gin.Context, uuid UUID)
	// Get legal entity by UUID
	// (GET /legal-entities/{uuid})
	GetLegalEntitiesUuid(c *gin.Context, uuid UUID)
	// Update legal entity by UUID
	// (PUT /legal-entities/{uuid})
	PutLegalEntitiesUuid(c *gin.Context, uuid UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetLegalEntities operation middleware
func (siw *ServerInterfaceWrapper) GetLegalEntities(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLegalEntitiesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLegalEntities(c, params)
}

// PostLegalEntities operation middleware
func (siw *ServerInterfaceWrapper) PostLegalEntities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostLegalEntities(c)
}

// DeleteLegalEntitiesUuid operation middleware
func (siw *ServerInterfaceWrapper) DeleteLegalEntitiesUuid(c *gin.Context) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid UUID

	err = runtime.BindStyledParameter("simple", false, "uuid", c.Param("uuid"), &uuid)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uuid: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLegalEntitiesUuid(c, uuid)
}

// GetLegalEntitiesUuid operation middleware
func (siw *ServerInterfaceWrapper) GetLegalEntitiesUuid(c *gin.Context) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid UUID

	err = runtime.BindStyledParameter("simple", false, "uuid", c.Param("uuid"), &uuid)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uuid: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLegalEntitiesUuid(c, uuid)
}

// PutLegalEntitiesUuid operation middleware
func (siw *ServerInterfaceWrapper) PutLegalEntitiesUuid(c *gin.Context) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid UUID

	err = runtime.BindStyledParameter("simple", false, "uuid", c.Param("uuid"), &uuid)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uuid: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutLegalEntitiesUuid(c, uuid)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/legal-entities", wrapper.GetLegalEntities)
	router.POST(options.BaseURL+"/legal-entities", wrapper.PostLegalEntities)
	router.DELETE(options.BaseURL+"/legal-entities/:uuid", wrapper.DeleteLegalEntitiesUuid)
	router.GET(options.BaseURL+"/legal-entities/:uuid", wrapper.GetLegalEntitiesUuid)
	router.PUT(options.BaseURL+"/legal-entities/:uuid", wrapper.PutLegalEntitiesUuid)
}
